In [1]:
#Importing Libraries
import warnings
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.svm import SVR 
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 

In [2]:
warnings.filterwarnings("ignore")

In [3]:
#Loading the Dataset
dataset = pd.read_csv("prep.csv")

In [4]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [5]:
dataset = pd.get_dummies(dataset, dtype = int, drop_first = True)

In [6]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [7]:
independent = dataset.drop("classification_yes",axis = 1)
dependent = dataset["classification_yes"]

In [8]:
independent

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [9]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [63]:
#Finding best Features Using RFE
n = 4
rfe_list = []
lr = LinearRegression()
svr_linear = SVR(kernel = 'linear')
#svr_non_liner = SVR(kernel = 'rbf') 
dt = DecisionTreeRegressor(random_state = 0)
rf = RandomForestRegressor(n_estimators = 10, random_state = 0)
 
#regression_models = [lr, svr_linear, svr_non_liner, dt,rf]  

regression_models = [lr, svr_linear, dt,rf]  

for model in regression_models:
    print(f"MODEL : {model}") 
    rfe_obj = RFE(model,n_features_to_select = n)
    rfe_model = rfe_obj.fit(independent,dependent)
    rfe_feature = rfe_model.transform(independent)
    rfe_list.append(rfe_feature)
    print(f"Completed")
    
rfe_list  

MODEL : LinearRegression()
Completed
MODEL : SVR(kernel='linear')
Completed
MODEL : DecisionTreeRegressor(random_state=0)
Completed
MODEL : RandomForestRegressor(n_estimators=10, random_state=0)
Completed


[array([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [1., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [1., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]]),
 array([[12.51815562,  4.70559701,  1.        ,  0.        ],
        [10.7       ,  4.70559701,  1.        ,  0.        ],
        [12.        ,  4.70559701,  0.        ,  0.        ],
        ...,
        [ 9.1       ,  3.4       ,  1.        ,  0.        ],
        [ 8.5       ,  4.70559701,  0.        ,  0.        ],
        [16.3       ,  4.9       ,  0.        ,  0.        ]]),
 array([[ 3.        , 12.51815562,  1.        ,  0.        ],
        [ 2.        , 10.7       ,  1.        ,  0.        ],
        [ 1.        , 12.        ,  0.        ,  0.        ],
        ...,
        [ 3.        ,  9.1       ,  1.        ,  0.        ],
        [ 

In [64]:
lr_acc = []
svr_linear_acc = []
svr_non_linear_acc = []
dt_acc = []
rf_acc = []
 

In [65]:
for i in rfe_list:
    x_train, x_test, y_train, y_test = train_test_split(i,dependent,test_size = 0.20, random_state = 0)

    #Linear Regresssion
    lr_regression = LinearRegression()
    lr_regression.fit(x_train, y_train)
    y_pred = lr_regression.predict(x_test)  
    lr_acc.append(r2_score(y_test,y_pred))
   
    #SVM Linear
    svc_regressor =  SVR(kernel = 'linear')
    svc_regressor.fit(x_train, y_train)
    y_pred = svc_regressor.predict(x_test)  
    svr_linear_acc.append(r2_score(y_test,y_pred))  
     
    #SVM Non Linear
    svc_n_regressor =  SVR(kernel = 'rbf')
    svc_n_regressor.fit(x_train, y_train)
    y_pred = svc_n_regressor.predict(x_test)  
    svr_non_linear_acc.append(r2_score(y_test,y_pred))  
     
    #Random Forest
    rf_classifier =  RandomForestRegressor(n_estimators = 10, random_state = 0)
    rf_classifier.fit(x_train, y_train)
    y_pred = rf_classifier.predict(x_test) 
    rf_acc.append(r2_score(y_test,y_pred))  

    #Decistion Tree
    dt_regressor =DecisionTreeRegressor(random_state = 0)
    dt_regressor.fit(x_train, y_train)
    y_pred = dt_regressor.predict(x_test)  
    dt_acc.append(r2_score(y_test,y_pred))  

In [66]:
rfe_data = pd.DataFrame(index = ["Linear","SVC","Random","DecisionTree"],columns = ["Linear","SVM_Linear","Random","DecisionTree"])

In [67]:
rfe_data

Linear SVM_Linear Random DecisionTree
Linear          NaN        NaN    NaN          NaN
SVC             NaN        NaN    NaN          NaN
Random          NaN        NaN    NaN          NaN
DecisionTree    NaN        NaN    NaN          NaN

In [68]:
for index,col in enumerate(rfe_data.index):    
    rfe_data["Linear"][col]          = lr_acc[0] 
    rfe_data["SVM_Linear"][col]             = svr_linear_acc[0]
    rfe_data["Random"][col]          = rf_acc[0]
    rfe_data["DecisionTree"][col]  = dt_acc[0]

 

In [61]:
#k = 3
rfe_data

Linear SVM_Linear    Random DecisionTree
Linear        0.521173   0.458333  0.520122     0.521173
SVC           0.521173   0.458333  0.520122     0.521173
Random        0.521173   0.458333  0.520122     0.521173
DecisionTree  0.521173   0.458333  0.520122     0.521173

In [69]:
#k = 4
rfe_data

Linear SVM_Linear   Random DecisionTree
Linear        0.642492   0.592002  0.80769     0.810842
SVC           0.642492   0.592002  0.80769     0.810842
Random        0.642492   0.592002  0.80769     0.810842
DecisionTree  0.642492   0.592002  0.80769     0.810842

In [54]:
#k = 5
rfe_data

Linear SVM_Linear    Random DecisionTree
Linear        0.651926   0.633419  0.794427     0.797934
SVC           0.651926   0.633419  0.794427     0.797934
Random        0.651926   0.633419  0.794427     0.797934
DecisionTree  0.651926   0.633419  0.794427     0.797934